In [2]:
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
import tqdm
import copy
from utils import *

plt.style.use('ggplot')

### Without Keras

In [75]:
movies = {
    'movie1': ['Action', 'Adventure'],
    'movie2': ['Comedy', 'Romance'],
    'movie3': ['Drama'],
    'movie4': ['Action', 'Drama'],
    'movie5': ['Comedy', 'Adventure'],
    'movie6': ['Action', 'Adventure'],
    'movie7': ['Comedy', 'Romance'],
    'movie8': ['Drama']
}


In [76]:
def get_recommendations(movie):
    # Get the genres of the movie
    genres = movies[movie]
    
    # Initialize an empty list to store recommended movies
    recommendations = []
    
    # Loop through all the movies
    for other_movie, other_genres in movies.items():
        # Skip the movie we are comparing to
        if other_movie == movie:
            continue
        
        # Calculate the similarity score between the genres of the two movies
        similarity_score = len(set(genres) & set(other_genres)) / float(len(set(genres) | set(other_genres)))
        
        # Add the movie and similarity score to the recommendations list if the similarity score is greater than 0.5
        if similarity_score > 0.5:
            recommendations.append((other_movie, similarity_score))
            
    # Sort the recommendations by similarity score in descending order
    recommendations = sorted(recommendations, key=lambda x: x[1], reverse=True)
    
    # Return the top 3 recommendations
    return recommendations[:3]


In [77]:
# Get recommendations for movie1
recommendations = get_recommendations('movie1')

# Print the recommended movies
for recommendation in recommendations:
    print(recommendation[0])


movie6


## Practice LinearLayer

In [5]:
class LinearLayer(Module):
    """
    A linear layer module which calculate (Wx + b).
    """

    def __init__(self, dim_in, dim_out, initializer, reg, alpha):
        """
        Args:
            - dim_in: input dimension,
            - dim_out: output dimension,
            - initializer: a function which get (dim_in, dim_out) and initialize
                a [dim_in x dim_out] matrix,
            - reg: L2-regularization flag
            - alpha: L2-regularization coefficient
        """
        self.dim_in = dim_in
        self.dim_out = dim_out
        self.params = {
            #########################################
            ##          Initialize parameters      ##
            ##              Your Code              ##
            #########################################
            'W': None,
            'b': None
        }
        self.grads = dict()
        self.cache = dict()

    def _forward(self, x):
        """
        linear forward function, calculate Wx+b for a batch of data

        Args:
            x : a batch of data
         Note:
            you need to store some values in cache to be able to
            calculate backward path.
        """
        #########################################
        ##              Your Code              ##
        #########################################
        y = None

        return y

    def backward(self, upstream):
        """
        get upstream gradient and returns downstream gradient

        Args:
            upstream : upstream gradient of loss w.r.t module output

        Note:
            you need to calculate gradient of loss w.r.t module input
            and parameters and store them in grads.
        """
        #########################################
        ##              Your Code              ##
        #########################################
        grad_b = None
        grad_w = None
        grad_x = None
        grad_reg = None

        self.grads = {
            'W': grad_w,
            'b': grad_b,
            'x': grad_x,
            'reg': grad_reg
        }

In [11]:
initializer = lambda x, y: np.random.normal(size=(y, x))

In [12]:
initializer

<function __main__.<lambda>(x, y)>

In [6]:
# sanity check, output must be from o(e-5)
initializer = lambda x, y: np.random.normal(size=(y, x))
linear = LinearLayer(5, 10, initializer, reg=True, alpha=0.001)
check_gradient_linear(linear, h=0.00001)

TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

In [ ]:
import numpy as np

class LinearLayer:
    def __init__(self, input_dim, output_dim):
        self.W = np.random.randn(input_dim, output_dim)  # Initialize weights
        self.b = np.zeros(output_dim)  # Initialize biases

    def forward(self, input_tensor):
        output_tensor = np.dot(input_tensor, self.W) + self.b  # Linear transformation
        return output_tensor


In [ ]:
# Create a linear layer with input size of 10 and output size of 5
linear_layer = LinearLayer(10, 5)

# Generate a random input tensor of size (batch_size=32, input_dim=10)
input_tensor = np.random.randn(32, 10)

# Apply the linear layer to the input tensor
output_tensor = linear_layer.forward(input_tensor)

# Print the shape of the output tensor
print(output_tensor.shape)  # Should print (32, 5)


In [3]:
import numpy as np

In [62]:
def ReLU(x):
  return np.maximum(0.0,x)

In [63]:
class LinearLayer_one:
    def __init__(self,input_dim,output_dim):
        self.w=np.random.randn(input_dim,output_dim)
        self.b=np.random.randn(output_dim)
    def feadforward(self,input_tensor):    
        output_tensor=np.dot(input_tensor,self.w)+self.b
        a1=ReLU(output_tensor)
        return a1

In [64]:
linear_layer_one=LinearLayer_one(10,5)

In [65]:
input_tensor=np.random.randn(2,10)

In [66]:
output_tensor_one=linear_layer_one.feadforward(input_tensor)
output_tensor_one

array([[0.        , 0.        , 0.        , 0.        , 0.53580293],
       [3.14522591, 3.383055  , 1.57220159, 6.71276427, 0.        ]])

In [61]:
print(linear_layer_one.w)
print(linear_layer_one.b)

[[-0.1367874  -0.23286428 -0.32579167 -0.53040458  0.75664197]
 [-1.11310777 -0.77411317 -0.02242892  0.35389126 -0.79398775]
 [ 1.20670768  0.79369066 -0.34488965 -1.24072979 -1.29276659]
 [-0.76635145 -0.72058776 -0.49380762 -0.52503982 -0.50781758]
 [ 0.96273641  1.20822114 -0.17574588 -0.5961679  -0.86746196]
 [-0.76499619 -1.16634606  0.30786189 -1.12932609 -0.65431162]
 [ 0.60338213 -0.502229   -1.69536933 -1.05050439 -0.35504377]
 [-1.65156502  0.86552438  1.20877213  0.69910553 -1.31588102]
 [-0.01137571  1.0146634   1.01867949  1.8898846  -0.55646994]
 [-0.49512409 -0.24811363 -1.27705421 -0.38223056  3.16535961]]
[-1.54861716 -0.44903904 -1.95012071  1.66703741  0.43372754]


In [51]:
output_grad = np.random.randn(*output_tensor.shape)

In [52]:
class LinearLayer:
    def __init__(self,input_dim,output_dim):
        self.w=np.random.randn(input_dim,output_dim)
        self.b=np.zeros(output_dim)
    def feadforward(self,input_tensor):  
        self.input_tensor=input_tensor  
        output_tensor=np.dot(input_tensor,self.w)+self.b
        return output_tensor
    def backward(self,output_grad):
        self.grade_w=np.dot(self.input_tensor.T,output_grad)
        self.grade_b=np.sum(output_grad,axis=0)
        
    def step(self,learning_rate):
        self.w -=learning_rate*self.grade_w
        self.b -= learning_rate*self.grade_b
        

In [53]:
# Create a linear layer with input size of 10 and output size of 5
linear_layer = LinearLayer(10, 5)

# Generate a random input tensor of size (batch_size=32, input_dim=10)
input_tensor = np.random.randn(32, 10)

# Apply the linear layer to the input tensor
output_tensor = linear_layer.feadforward(input_tensor)

# Generate a random gradient of the same shape as the output tensor
output_grad = np.random.randn(*output_tensor.shape)

# Compute the gradient of the input tensor using the backward method
input_grad = linear_layer.backward(output_grad)

# Update the weights and biases using the step method with a learning rate of 0.1
linear_layer.step(0.1)

# Print the updated weights and biases
print(linear_layer.w)
print(linear_layer.b)


[[-0.41094223 -0.0262169  -1.07205475 -0.68575593  0.82532334]
 [ 0.04871429  0.91754414  0.1522285   0.76478841  1.08026645]
 [ 0.46206882  1.53223458 -1.28646262  1.45024206 -0.77442344]
 [-0.7135635  -0.73871292 -0.28803107  0.31147536 -1.06405336]
 [-1.34895591  1.47565554  1.63988463  0.30049018  1.52288718]
 [-0.57776417  0.05235745 -0.65990779 -1.45893937  1.11885795]
 [-0.10361368  0.19886739  0.2860816   1.32978821  2.10717046]
 [ 1.68828836  0.39978042 -1.42240389 -0.08420041  0.2872899 ]
 [ 0.39717345 -0.76570608  0.84521165  1.98575885 -1.08113079]
 [-0.74165673 -1.3471711  -0.28278399  0.85756265 -0.07763194]]
[ 0.20108655  0.10100027  0.43292934  0.09417513 -0.13156326]


### Implimented with Keras

In [5]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Input
from keras import Sequential
from keras.losses import MeanSquaredError, BinaryCrossentropy
from keras.activations import sigmoid
import numpy as np

In [6]:
linear_layer = tf.keras.layers.Dense(units=1, activation = 'linear', )

In [7]:
linear_layer.get_weights()

[]

In [8]:
X_train = np.array([[1.0], [2.0]], dtype=np.float32)      
Y_train = np.array([[300.0], [500.0]], dtype=np.float32)

In [10]:
set_w = np.array([[200]])
set_b = np.array([100])

In [12]:
prediction_tf = linear_layer(X_train)
prediction_np = np.dot( X_train, set_w) + set_b

In [13]:
prediction_tf

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-1.5891801],
       [-3.1783602]], dtype=float32)>

In [14]:
prediction_np

array([[300.],
       [500.]])

In [15]:
linear_layer.set_weights([set_w,set_b])

In [16]:
prediction_tf=linear_layer(X_train)

In [17]:
prediction_tf

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[300.],
       [500.]], dtype=float32)>

### Use Sequential

In [18]:
model = Sequential(
    [
        tf.keras.layers.Dense(1, input_dim=1,  activation = 'sigmoid', name='L1')
    ]
)

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [24]:
set_w = np.array([[200]])
set_b = np.array([100])

In [25]:
model.set_weights([set_w, set_b])

In [26]:
model.predict(X_train)

1/1 [==============================] - 0s 45ms/step


array([[1.],
       [1.]], dtype=float32)

### Let's Building an Image Classifier